# Generated by Django 5.2.11 on 2026-03-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0002_alter_jamsession_id_alter_participation_id_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showed_up', models.BooleanField()),
                ('would_jam_again', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jams.jamsession')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reviewer', 'reviewee', 'jam_session')},
            },
        ),
    ]
