# Generated by Django 5.2.11 on 2026-03-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_add_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamsession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jamsession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
