# Generated by Django 5.2.11 on 2026-02-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_linkedin_url_userprofile_tiktok_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
