# Generated by Django 5.2.11 on 2026-03-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strike_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
